insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Le petit soldat', '978-2-7560-9607-0');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'L''autoroute', '978-2-7234-1216-2');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Cycle wars', '978-2-7234-1395-4');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Les chasseurs', '978-2-7234-1477-7');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Le réveil', '978-2-7234-1478-4');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Désespoir', '978-2-7234-1490-6');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Chaos', '978-2-7234-1503-3');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Révélations', '978-2-7234-1522-4');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Déluge', '978-2-7234-1546-0');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Visions', '978-2-7234-1552-1');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Revanche', '978-2-7234-1574-3');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Chocs', '978-2-7234-1588-0');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Lumières', '978-2-7234-1689-4');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Feux', '978-2-7234-1905-5');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'L''Île maudite', '978-2-2033-1206-7');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Le tonnerre dans les veines', '978-2-8094-6666-9');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Les seigneurs de Midgard', '978-2-8094-6863-2');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Nao', '978-2-8478-9525-4');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Planète bleue', '978-2-8405-5920-7');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Le Mégophias', '978-2-8478-9527-8');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Corail noir', '978-2-8405-5010-5');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Projet Atalanta', '978-2-8405-5227-7');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'Peur abyssale', '978-2-3657-7072-9');
insert into comic_book (comic_book_id, title, isbn  ) values (uuid_in(md5(random()::text || clock_timestamp()::text)::cstring), 'L''Autre Ligue', '978-2-3657-7279-2');